server:
  port: 8099

dbInfoReceiver:
  url: http://localhost:8090/clientInfo

photoReceiver:
  url: http://localhost:8092/sync/adapter587sync

photoStore:
  url: http://photostore.vtb.ru:8899/
logging:
  level:
    org:
      springframework:
        web: DEBUG
        ws:
          client:
            MessageTracing:
              sent: trace
              received: trace
          server:
            MessageTracing:
              sent: trace
              received: trace
